// <auto-generated />
using System;
using AplikacjaDoPlanowaniaZadan.Server.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplikacjaDoPlanowaniaZadan.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241030175901_inicjalizacja")]
    partial class inicjalizacja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AplikacjaDoPlanowaniaZadan.Server.DataModels.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 10, 30, 18, 59, 0, 642, DateTimeKind.Local).AddTicks(1181),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem",
                            DueTo = new DateTime(2024, 10, 30, 18, 59, 0, 642, DateTimeKind.Local).AddTicks(1220),
                            Name = "Dupa jasiu pierdzi stasiu... Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturie",
                            Priority = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 10, 30, 18, 59, 0, 642, DateTimeKind.Local).AddTicks(1222),
                            Description = "Odrob prace domowa z matematyki i fizyki ",
                            DueTo = new DateTime(2024, 10, 31, 18, 59, 0, 642, DateTimeKind.Local).AddTicks(1224),
                            Name = "Praca domowa",
                            Priority = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 10, 30, 18, 59, 0, 642, DateTimeKind.Local).AddTicks(1229),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula,",
                            DueTo = new DateTime(2024, 10, 30, 18, 59, 0, 642, DateTimeKind.Local).AddTicks(1231),
                            Name = "Przedszkole",
                            Priority = 0,
                            Status = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
